/* tables */

\i entities/users.sql
\i entities/roles.sql
\i entities/comments.sql
\i entities/threads.sql
\i entities/topics.sql
\i entities/trash.sql
\i entities/reactions.sql
\i entities/pictures.sql
\i entities/videos.sql
\i entities/polls.sql
\i entities/captcha.sql

/* constraints */

\i entities/references.sql

/* functions */

\i functions/throw_in_trash.sql
\i functions/vote_in_poll.sql

/* triggers */

\i triggers/creating_comment.sql